[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
[build]
target = "x86_64-rose-os.json"
[source.crates-io]
index = "https://github.com/rust-lang/crates.io-index" # I set the source to the official github index
[http]
proxy = "" # leaving this as a blank string resets proxy to default